env:
  TERM: xterm-256color

scrolling:
  history: 100000

font:
  size: 8.0
  normal:
    family: MesloLGM NF
    style: Regular

live_config_reload: true

key_bindings:
 - { key: K, mods: Control, mode: ~Vi|~Search, chars: "\x0c" }
 - { key: K, mods: Control, mode: ~Vi|~Search, action: ClearHistory }
