{{ $fontsDir := ".fonts" -}}
{{ if eq .chezmoi.os "darwin" -}}
  {{ $fontsDir = "Library/Fonts" -}}
{{ end -}}

[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
  type = "archive"
  url = "https://github.com/romkatv/powerlevel10k/archive/v1.16.1.tar.gz"
  exact = true
  stripComponents = 1

["{{ $fontsDir }}/JetBrainsMono"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip"
  exact = true
["{{ $fontsDir }}/Meslo"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Meslo.zip"
  exact = true
["{{ $fontsDir }}/SourceCodePro"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/SourceCodePro.zip"
  exact = true
