#!/usr/bin/env bash

nvim +PlugInstall +qall < /dev/tty

if [ -d "$HOME/.fzf" ]; then
    pushd "$HOME/.fzf"
    ./install --no-update-rc
    popd
fi

if [ "`uname -s`" = "Darwin" ]; then
  find "$HOME/.fonts" -name '*.ttf' -exec cp {} "$HOME/Library/Fonts/" \;
fi
