theme = "native"
#theme = "nord-dark"
icons = "awesome"

[[block]]
block = "cpu"
interval = 1
format="{utilization}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_avail}"
clickable = false

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
format = "{path} {available}"
interval = 20
warning = 50.0
alert = 20.0

[[block]]
block = "disk_space"
path = "/mnt/data"
info_type = "available"
unit = "GB"
format = "{path} {available}"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "enp0s31f6"
format = "{ip} {speed_up;M} {speed_down;M}"

[[block]]
block = "net"
device = "tun0"
format = "{ip}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%H:%M %d.%m.%Y"
